---
image:
  name: ansible:2.7-1

stages:
  - test


services:
  - name: basenode:1.0
    alias: controller
    command: [ "/sbin/init" ]

before_script:
  - mkdir ~/.ssh
  - cp /home/ansible/.ssh/id_rsa ~/.ssh/id_rsa

test_result:
  stage: test
  script:
    - ansible-playbook -i tests/inventory tests/test.yml 