
- block:
  - name: check database existence
    command: "{{ sql }} -e 'use {{ database_name }};'"
    failed_when: false
    register: ret
  
  - name: create databases
    command: "{{ sql }} -e 'CREATE DATABASE {{ database_name }};'"
    when: ret.rc != 0
  
  - name: check permission to localhost
    command: >
      {{ sql }} -e 'SELECT * FROM mysql.user WHERE Host = "localhost" and User = "{{ database_user }}";'
    register: user_localhost
  
  - name: glant on localhost
    command: >
        {{ sql }} -e \
          "GRANT ALL PRIVILEGES ON {{ database_name }}.*  \
           TO '{{ database_user }}'@'localhost'  \
           IDENTIFIED BY '{{ database_pass }}';"
    when: user_localhost.stdout_lines | length < 3
  
  - name: check permission to %
    command: >
      {{ sql }} -e 'SELECT * FROM mysql.user WHERE Host = "%" and User = "{{ database_user }}";'
    register: user_any
  
  - name: grant on %
    command: >
       {{ sql }} -e  \
        "GRANT ALL PRIVILEGES ON {{ database_name }}.*  \
         TO '{{ database_user }}'@'%'  \
         IDENTIFIED BY '{{ database_pass }}';"
    when: user_any.stdout_lines | length < 3

  delegate_to: "{{ minimal_openstack_controller_management_ip }}"