
- name: install neutron agent packages
  yum:
    name:
      - openstack-neutron-linuxbridge
      - ebtables 
      - ipset
    state: present

- name: configure neutron.conf
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: DEFAULT,
      option: transport_url,
      value: "rabbit://openstack:{{ minimal_openstack_rabbitmq_password }}@controller"
    }
    - {
      section: DEFAULT,
      option: auth_strategy,
      value: keystone
    }
    - {
      section: keystone_authtoken,
      option: www_authenticate_uri,
      value: http://controller:5000/
    }
    - {
      section: keystone_authtoken,
      option: auth_url,
      value: http://controller:5000/
    }
    - {
      section: keystone_authtoken,
      option: memcached_servers,
      value:  controller:11211
    }
    - {
      section: keystone_authtoken,
      option: auth_type,
      value: password
    }
    - {
      section: keystone_authtoken,
      option: project_domain_name,
      value: Default
    }
    - {
      section: keystone_authtoken,
      option: user_domain_name,
      value: Default
    }
    - {
      section: keystone_authtoken,
      option: project_name,
      value: service
    }
    - {
      section: keystone_authtoken,
      option: username,
      value: neutron
    }
    - {
      section: keystone_authtoken,
      option: password,
      value: "{{ minimal_openstack_neutron_user_password }}"
    }
    - {
      section: oslo_concurrency,
      option: lock_path,
      value: /var/lib/neutron/tmp
    }

- name: configure linuxbridge_agent.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: linux_bridge,
      option: physical_interface_mappings,
      value: "provider:{{ minimal_openstack_compute_provider_physical_network_interface }}"
    }
    - { 
      section: vxlan,
      option: enable_vxlan,
      value: "true"
    }
    - { 
      section: vxlan,
      option: local_ip,
      value:  "{{ minimal_openstack_compute_management_ip }}"
    }
    - { 
      section: vxlan,
      option: l2_population,
      value:  "true"
    }
    - { 
      section: securitygroup,
      option: enable_security_group,
      value:  "true"
    }
    - { 
      section: securitygroup,
      option: firewall_driver,
      value:  neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
    }

- name: load br_netfilter
  copy:
    src: br_netfilter.modules
    dest: /etc/sysconfig/modules/br_netfilter.modules
    owner: root
    group: root
    mode: 0755

- command: modprobe br_netfilter

- name: enable bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: enable bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1

- name: enable neutron-linuxbridge-agent.service
  service:
    name: neutron-linuxbridge-agent.service
    enabled: yes
    state: restarted

- name: compute service restart
  service:
    name: openstack-nova-compute.service
    state: restarted